version: '3'

services:
    app:
        image: ferfabricio/php-dev:1.0
        container_name: app
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - app-network
        depends_on:
            - db
    db:
        image: postgres:latest
        container_name: db
        restart: unless-stopped
        tty: true
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: dbpass
            POSTGRES_USER: dbuser
            POSTGRES_DB: dbname
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
            - dbdata:/var/lib/postgresql/data/pgdata
        networks:
            - app-network
networks:
    app-network:
volumes:
    dbdata:
        driver: local
