version: '3'

services:
    app_test:
        image: ferfabricio/php-dev:1.0
        container_name: app_test
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app_test
        working_dir: /var/www
        extra_hosts:
          - "host.docker.internal:host-gateway"
        volumes:
            - ./:/var/www
        networks:
            - test-network
        depends_on:
            - db_test
    db_test:
        image: postgres:latest
        container_name: db_test
        restart: unless-stopped
        tty: true
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: dbpass
            POSTGRES_USER: dbuser
            POSTGRES_DB: dbname
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
            - dbdata:/var/lib/postgresql/data/pgdata
        networks:
            - test-network
networks:
    test-network:
volumes:
    dbdata:
        driver: local
